name: Model Sanity Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and set up DVC
        env:
          GCP_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}
        run: |
          # 💡 CORRECTED: Consolidating all setup commands into one block
          # to ensure DVC and its dependencies are active for all DVC commands.
          
          # Create and activate virtual environment
          python -m venv .venv
          source .venv/bin/activate
          
          # Install all dependencies, including DVC with GCS support
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gcs]" shap fairlearn evidently
          
          # Set up GCP credentials
          set -e
          echo "$GCP_B64" > gcp-key.json
          
          # Initialize DVC and configure remote
          dvc init
          dvc remote add -d gcsremote gcs://mlops-week9
          dvc remote modify gcsremote gcp_service_account_keyfile gcp-key.json
          
          # Authenticate with gcloud and pull data
          echo "Installing Google Cloud CLI..."
          sudo apt-get update && sudo apt-get install -y google-cloud-cli
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project workoutvideos
          
          echo "Running DVC pull:"
          dvc pull -v

      - name: Data Quality Check
        id: label_check
        run: |
          source .venv/bin/activate
          echo "## Data Quality Report" >> report.md
          python src/check_labels.py --data-path data/iris.csv >> report.md

          SUSPICIOUS_COUNT=$(grep "Found" report.md | awk '{print $2}')
          echo "Suspicious labels found: $SUSPICIOUS_COUNT"
          echo "count=$SUSPICIOUS_COUNT" >> "$GITHUB_OUTPUT"

      - name: Validate Label Quality
        run: |
          echo "Checking if suspicious count is within tolerance..."
          if [ ${{ steps.label_check.outputs.count }} -gt 10 ]; then
            echo "Error: High number of suspicious labels detected (${{ steps.label_check.outputs.count }}). Aborting workflow."
            exit 1
          else
            echo "Data quality check passed. Proceeding with training."
          fi

      - name: Run Training and Core Evaluation
        run: |
          source .venv/bin/activate
          python src/train.py
          python src/evaluate.py
          python src/plot_metrics.py

      - name: Run Tests
        run: |
          source .venv/bin/activate
          echo "## Test Results" >> report.md
          pytest --tb=short --disable-warnings >> report.md 2>&1 || echo "Tests failed" >> report.md
          echo "Tests completed on $(date)" >> report.md

      ### --- NEW RESPONSIBLE AI STAGE --- ###
      - name: Run Responsible AI Checks
        run: |
          source .venv/bin/activate
          echo "## Responsible AI Reports" >> report.md

          echo "### 1. Generating SHAP Explanations..." >> report.md
          python src/generate_explanations.py >> report.md

          echo "### 2. Checking Fairness (Fairlearn)..." >> report.md
          python src/check_fairness.py >> report.md

          echo "### 3. Checking Data Drift (Evidently)..." >> report.md
          python src/check_drift.py >> report.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            artifacts/
            report.md

      - name: Setup CML
        uses: iterative/setup-cml@v2
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source .venv/bin/activate
          echo "## Model Explainability (SHAP)" >> report.md
          echo "![SHAP Summary](./artifacts/shap_summary_global.png)" >> report.md

          cml comment create report.md
